name: llvmlite_win-arm64_wheel_builder
on:
  push:
    branches:
      - WoA
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true
env:
  VALIDATION_PYTHON_VERSION: "3.12"
  ARTIFACT_RETENTION_DAYS: 7
  LLVM_VERSION: "15.0.7"
  LLVM_INSTALL_PREFIX: "C:\\llvm-arm64"
jobs:
  win-arm64-build:
    name: win-arm64-build
    runs-on: windows-11-arm
    defaults:
      run:
        shell: bash -elx {0}
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
      fail-fast: false
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: arm64

      - name: Install 7zip & Ninja
        run: |
          choco install ninja 7zip
          ninja --version

      - name: Download and Extract Prebuilt LLVM for ARM64
        shell: pwsh
        run: |
          $zipUrl = "https://github.com/lowkeyrossi/Clang-LLVM-15.0.7-for-Win-Arm64/releases/download/Release15.0.7/llvm-arm64.zip"
          $zipPath = "llvm-arm64.zip"
          Invoke-WebRequest -Uri $zipUrl -OutFile $zipPath
          Expand-Archive -Path $zipPath -DestinationPath "C:\llvm-unpack"
          Get-ChildItem "C:\llvm-unpack" | ForEach-Object { Write-Output "Extracted: $($_.FullName)" }

          # Try to find the actual folder that was extracted
          $extractedDir = Get-ChildItem "C:\llvm-unpack" | Where-Object { $_.PSIsContainer } | Select-Object -First 1
          if (-not $extractedDir) {
            throw "Failed to find extracted directory"
          }

          Rename-Item -Path $extractedDir.FullName -NewName "llvm-arm64"
          Move-Item -Path "C:\llvm-unpack\llvm-arm64" -Destination "C:\llvm-arm64"


      - name: Setup vcpkg and install libxml2
        run: |
          git clone https://github.com/Microsoft/vcpkg.git
          cd vcpkg
          ./bootstrap-vcpkg.bat
          ./vcpkg install libxml2:arm64-windows
          echo "VCPKG_ROOT=$(pwd)" >> $GITHUB_ENV

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build wheel setuptools

      - name: Configure environment for llvmlite build
        run: |
          echo "LLVM_CONFIG=$LLVM_INSTALL_PREFIX/bin/llvm-config" >> $GITHUB_ENV
          echo "LLVM_DIR=$LLVM_INSTALL_PREFIX/lib/cmake/llvm" >> $GITHUB_ENV
          echo "CMAKE_PREFIX_PATH=$LLVM_INSTALL_PREFIX" >> $GITHUB_ENV
          echo "XML2_ROOT=$VCPKG_ROOT/installed/arm64-windows" >> $GITHUB_ENV
          echo "$LLVM_INSTALL_PREFIX/bin" >> $GITHUB_PATH

      - name: Build wheel
        run: |
          python -m build

      - name: Upload llvmlite wheel
        uses: actions/upload-artifact@v4
        with:
          name: llvmlite-win-arm64-py${{ matrix.python-version }}
          path: dist/*.whl
          compression-level: 0
          retention-days: ${{ env.ARTIFACT_RETENTION_DAYS }}
          if-no-files-found: error

      - name: Show Workflow Run ID
        run: "echo \"Workflow Run ID: ${{ github.run_id }}\""
